import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Banner from "../components/Banner";
import Container from "../components/Container";

export default function Home() {
  const dispatch = useDispatch();
  const cartProducts = useSelector((state) => state.products);

  useEffect(() => {
    if (cartProducts.length === 0) {
      (async () => {
        const response = await fetch("https://fakestoreapi.com/products");
        const products = await response.json();
        dispatch({
          type: "create",
          payload: products,
        });
      })();
    }
  }, []);
  return (
    <div className="h-screen">
      <Head>
        <title>Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cartProducts.length > 0 && <Banner data={cartProducts[0]} />}
      <Container datas={cartProducts} />
    </div>
  );
}

// export async function getStaticProps() {
//   const response = await fetch("https://fakestoreapi.com/products");
//   const products = await response.json();
//   return {
//     props: {
//       products,
//     },
//   };
// }
